[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
tuple-map = "0.4.0"
range-set = "0.0.9"
range-collections = "0.2.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false