[package]
name = "Advent"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "day3"
path = "src/2022/day3/src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
